server:
  port: 8195
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**
  config:
    import: configserver:http://localhost:8196

## Now we will fetch this from git default file application.yml ,with the help of config server
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8194/eureka

okta:
  oauth2:
    issuer: https://dev-54760333.okta.com/oauth2/default
    audience: api://default
    client-id: 0oadjzmdbtPbaNmX15d7
    client-secret: V5E5gNVrgdEoIPGuqfC7zxCtTOU2btY7iKHgn3DXuaNBH9rpOyyoWndEA0ys29Eu
    scopes: openid, profile, email, offline_access