server:
  port: 8196

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/subhjeetsingh/microservices-configurations
          clone-on-start: true

## As config server first registers itself to service registry then fetch configurations , so eureka props needs here
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8194/eureka